artists : 
  type: rest
  resource:     "AdminBundle:ArtisteRest"
  name_prefix:  api_
  
users : 
  type: rest
  resource:     "AdminBundle:UserRest"
  name_prefix:  api_
  
albums : 
  type: rest
  resource:     "AdminBundle:AlbumRest"
  name_prefix:  api_