admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

public:
    resource: "@PublicBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"