<?php

namespace PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArtisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisteRepository extends EntityRepository
{

	public function getArtistes($idTag)
	{
		$qb = $this->createQueryBuilder('a');

    // On fait une jointure avec l'entité Categorie, avec pour alias « c »
		$qb ->join('a.tags', 't')
        ->where($qb->expr()->in('t.id', $idTag)); // Puis on filtre sur le nom des catégories à l'aide d'un IN

    // Enfin, on retourne le résultat
        return $qb->getQuery()
        ->getResult();
    }
    
}
